### ISSUE TITLE
Cannot set region for anything

### ISSUE THREAD

**Issue by mikaelsand** [pacodelacruz/serverless-request-bin-azure-functions#1]
Except for the Application Insights, there is no way of deciding where the function, storage etc should be placed. Mine was placed in west US.

**Comment by pacodelacruz** [comment]
Hi @mikaelsand 

Thanks for your feedback. 
As mentioned in the README.md

> If you are planning to deploy the Serverless Request Bin in a new resource group, it is highly recommended creating the resource group in advance, so you can choose the region for the resource group. At the time of writing, the deploy button option does not allow you to choose the region for a new resource group.

This is a limitation of the `deploy.azure.com` service. That's why I recommend to create the resource group in advance. 

I'm updating the README.md to make it a bit clearer. 

Additionally, I strongly recommend you to use the latest Serverless Request Bin that is stateful by using Durable Entities, here https://github.com/pacodelacruz/serverless-request-bin-durable-functions.

**Comment by pacodelacruz** [comment]
Closing the issue as this is a limitation of the azure platform and can be solved by creating the resource group in advance in the desired region.
